name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H 3.107.86.145 >> ~/.ssh/known_hosts

      - name: Connect to EC2 and Deploy
        run: |
          ssh -i ~/.ssh/ec2_key.pem ubuntu@3.107.86.145 << 'EOF'
            cd backend
            git pull origin main
            pnpm install
            pm2 restart backend
          EOF
