name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH into EC2 and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i "pnBackend.pem" ubuntu@<EC2_PUBLIC_IP> <<EOF
            cd backend
            git pull origin main
            pnpm install
            pm2 restart backend
          EOF
